set -sg escape-time 0

set -g base-index 1
setw -g pane-base-index 1
set -g extended-keys on

#set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:usstyle"
set -as terminal-features 'xterm*:extkeys'

#set-option -ga terminal-overrides ",xterm*:Tc"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# helper: jump to window N or create it
# usage: run-shell "tmux select-window -t :N 2>/dev/null || tmux new-window -c '#{pane_current_path}' -t :N"

set -g base-index 1
setw -g pane-base-index 1

bind-key -n F1  run-shell 'tmux select-window -t :1  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :1'
bind-key -n F2  run-shell 'tmux select-window -t :2  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :2'
bind-key -n F3  run-shell 'tmux select-window -t :3  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :3'
bind-key -n F4  run-shell 'tmux select-window -t :4  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :4'
bind-key -n F5  run-shell 'tmux select-window -t :5  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :5'
bind-key -n F6  run-shell 'tmux select-window -t :6  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :6'
bind-key -n F7  run-shell 'tmux select-window -t :7  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :7'
bind-key -n F8  run-shell 'tmux select-window -t :8  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :8'
bind-key -n F9  run-shell 'tmux select-window -t :9  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :9'
bind-key -n F10 run-shell 'tmux select-window -t :0  2>/dev/null || tmux new-window -c "#{pane_current_path}" -t :0'

set -g mouse on
set -g status-interval 30
set -g status-right '#(/home/anatoliyi/.local/bin/tmux-battery)'
