font_family JetBrainsMono Nerd Font
font_size 12

#tab_bar_style fade
#draw_minimal_borders yes
#resize_in_steps yes
placement_strategy top-left

# BEGIN_KITTY_THEME
# Arthur
include current-theme.conf
# END_KITTY_THEME
background #000000

