# -*- conf -*-

font=JetBrainsMono Nerd Font:size=12.5
initial-color-theme=dark

[colors-dark]
foreground=ddeedd
background=000000

selection-foreground=1c1c1c
selection-background=4d4d4d
cursor=1c1c1c e2bbef

regular0=3d352a
regular1=cd5c5c
regular2=86af80
regular3=e8ae5b
regular4=6495ed
regular5=deb887
regular6=b0c4de
regular7=bbaa99

bright0=554444
bright1=cc5533
bright2=88aa22
bright3=ffa75d
bright4=87ceeb
bright5=996600
bright6=b0c4de
bright7=ddccbb

[text-bindings]
\x1b[5;30012~ = Control+Tab
\x1b[6;30012~ = Control+Shift+Tab Control+ISO_Left_Tab
\x1b[7;30012~ = Control+Shift+t
\x1b[8;30012~ = Control+Shift+w
