й quit
Й quit-watch-later
з cycle pause
ю frame-step
б frame-back-step
SPACE cycle pause
> playlist-next
< playlist-prev
щ show-progress
Щ no-osd cycle-values osd-level 3 1
ш script-binding stats/display-stats
Ш script-binding stats/display-stats-toggle
я add sub-delay -0.1
ч add sub-delay +0.1
ь cycle mute
9 add volume -2
0 add volume 2
х multiply speed 1/1.1
ъ multiply speed 1.1
а cycle fullscreen
ы screenshot
м cycle sub-visibility
о cycle sub
№ cycle audio
_ cycle video
